### ISSUE TITLE
No such file or directory: '/data1/timer/JAS/datasets/VIS_IR/ir/0.png' 

### ISSUE THREAD

**Issue by Desolatexxx** [Linfeng-Tang/SuperFusion#1]
Traceback (most recent call last):   File "test.py", line 4, in <module>     from model import SuperFusion   File "G:\imagePython\SuperFusion\model.py", line 10, in <module>     from utils.utils import RGB2YCrCb, YCbCr2RGB   File "G:\imagePython\SuperFusion\utils\utils.py", line 55, in <module>     img = Image.open("/data1/timer/JAS/datasets/VIS_IR/ir/0.png")   File "F:\softwareTool\Anaconda\Anaconda\envs\py36\lib\site-packages\PIL\Image.py", line 2975, in open     fp = builtins.open(filename, "rb") FileNotFoundError: [Errno 2] No such file or directory: '/data1/timer/JAS/datasets/VIS_IR/ir/0.png'

**Comment by Linfeng-Tang** [comment]
You need to set the path according to your dataset.
